-- Выборка всех данных из таблиц
SELECT * FROM AUTHORS;
SELECT * FROM GENRES;
SELECT * FROM PUBLISHERS;

-- Удаление строки из таблицы
DELETE FROM AUTHORS WHERE AUTHOR_NAME = ?;
DELETE FROM GENRES WHERE GENRE_NAME = ?;
DELETE FROM PUBLISHERS WHERE PUBLISHER_NAME = ?;

-- Добавление строки в таблицу
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES (?);
INSERT INTO GENRES (GENRE_NAME) VALUES (?);
INSERT INTO PUBLISHERS (PUBLISHER_NAME) VALUES (?);

-- Изменение строки в таблице
UPDATE AUTHORS SET AUTHOR_NAME = ? WHERE AUTHOR_NAME = ?;
UPDATE GENRES SET GENRE_NAME = ? WHERE GENRE_NAME = ?;
UPDATE PUBLISHERS SET PUBLISHER_NAME = ? WHERE PUBLISHER_NAME = ?;
