-- Создание записи о книге в каталоге
INSERT INTO BOOK_CATALOG (BOOK_ID, TITLE, YEAR_PUBLISHED, AUTHOR_NAME, GENRE_NAME, PUBLISHER_NAME)
VALUES (C##DENIS.BOOK_CATALOG_SEQ.NEXTVAL, ?, ?, ?, ?, ?);

-- Получение информации о книге по ID
SELECT * FROM BOOK_CATALOG WHERE BOOK_ID = ?;

-- Обновление информации о книге в каталоге
UPDATE BOOK_CATALOG
SET TITLE = ?, YEAR_PUBLISHED = ?, AUTHOR_NAME = ?, GENRE_NAME = ?, PUBLISHER_NAME = ?
WHERE BOOK_ID = ?;

-- Удаление информации о книге из каталога по ID
DELETE FROM BOOK_CATALOG WHERE BOOK_ID = ?;

-- Получение списка всех книг определенного издателя
SELECT * FROM BOOK_CATALOG WHERE PUBLISHER_NAME = ?;

-- Получение списка всех книг определенного года выпуска
SELECT * FROM BOOK_CATALOG WHERE YEAR_PUBLISHED = ?;

-- Получение списка всех книг определенного жанра
SELECT * FROM BOOK_CATALOG WHERE GENRE_NAME LIKE '%?%';

-- Получение списка всех книг определенного автора
SELECT * FROM BOOK_CATALOG WHERE AUTHOR_NAME LIKE '%?%';

-- Получение списка книг по части названия (частичный поиск)
SELECT * FROM BOOK_CATALOG WHERE TITLE LIKE '%?%';

-- Получение количества книг присутствующих в библиотеке по book_id
SELECT BC.BOOK_ID, BC.TITLE, BC.YEAR_PUBLISHED, BC.AUTHOR_NAME, BC.GENRE_NAME, BC.PUBLISHER_NAME, COUNT(BI.INVENTORY_ID) AS NUM_OF_BOOKS
FROM BOOK_CATALOG BC
LEFT JOIN BOOK_INVENTORY BI ON BC.BOOK_ID = BI.BOOK_ID
WHERE BC.BOOK_ID = ?
GROUP BY BC.BOOK_ID, BC.TITLE, BC.YEAR_PUBLISHED, BC.AUTHOR_NAME, BC.GENRE_NAME, BC.PUBLISHER_NAME;

-- Получение количества книг присутствующих в библиотеке
SELECT BC.BOOK_ID, BC.TITLE, BC.YEAR_PUBLISHED, BC.AUTHOR_NAME, BC.GENRE_NAME, BC.PUBLISHER_NAME, COUNT(BI.INVENTORY_ID) AS NUM_OF_BOOKS
FROM BOOK_CATALOG BC
LEFT JOIN BOOK_INVENTORY BI ON BC.BOOK_ID = BI.BOOK_ID
GROUP BY BC.BOOK_ID, BC.TITLE, BC.YEAR_PUBLISHED, BC.AUTHOR_NAME, BC.GENRE_NAME, BC.PUBLISHER_NAME;

-- Получение количества книг присутствующих в библиотеке с определенным статусом
SELECT BC.BOOK_ID, BC.TITLE, BC.YEAR_PUBLISHED, BC.AUTHOR_NAME, BC.GENRE_NAME, BC.PUBLISHER_NAME, COUNT(CASE WHEN BI.STATUS = ? THEN BI.INVENTORY_ID ELSE NULL END) AS NUM_OF_BOOKS
FROM BOOK_CATALOG BC
LEFT JOIN BOOK_INVENTORY BI ON BC.BOOK_ID = BI.BOOK_ID
GROUP BY BC.BOOK_ID, BC.TITLE, BC.YEAR_PUBLISHED, BC.AUTHOR_NAME, BC.GENRE_NAME, BC.PUBLISHER_NAME;

-- Получение количества книг присутствующих в библиотеке с определенным статусом и book_id
SELECT BC.BOOK_ID, BC.TITLE, BC.YEAR_PUBLISHED, BC.AUTHOR_NAME, BC.GENRE_NAME, BC.PUBLISHER_NAME, COUNT(CASE WHEN BI.STATUS = ? THEN BI.INVENTORY_ID ELSE NULL END) AS NUM_OF_BOOKS
FROM BOOK_CATALOG BC
LEFT JOIN BOOK_INVENTORY BI ON BC.BOOK_ID = BI.BOOK_ID
WHERE BC.BOOK_ID = ?
GROUP BY BC.BOOK_ID, BC.TITLE, BC.YEAR_PUBLISHED, BC.AUTHOR_NAME, BC.GENRE_NAME, BC.PUBLISHER_NAME;
